spring:
  application:
    name: workout
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password :
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: ${mysql_rds_url}
     username: ${mysql_rds_id}
     password: ${mysql_rds_pw}
  servlet:
    mime-mappings:
      otf: "font/otf"
  kafka:
    producer:
      bootstrap-servers: ${kafka_connection_ip}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    creativeprj.creative: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

openai:
  api:
    key: ${openai_api_key}

youtube:
  api:
    key: ${youtube_api_key}

ec2:
  ip : ${local_ip}



